"""Schema test for run_model.py output format.

Validates the output JSON schema against a committed fixture generated by:
  python scripts/run_model.py --model openai-community/gpt2 --output gpt-2-124m_smoke-fixture.json \
    --ex-dim 10 --batch-size 4 --layers-per-pass 6 --attn-impl sdpa --seeds 2 --skip-c4 --max-docs 200

No network access, no model download, no GPU required.
"""

import json
from pathlib import Path

import pytest

FIXTURES_DIR = Path(__file__).resolve().parent / "fixtures"
FIXTURE_FILE = "gpt-2-124m_smoke-fixture.json"


@pytest.fixture(scope="module")
def smoke_results():
    """Load committed fixture."""
    path = FIXTURES_DIR / FIXTURE_FILE
    assert path.exists(), (
        f"Fixture missing: {path}. Regenerate with: python scripts/run_model.py --model openai-community/gpt2 --output {FIXTURE_FILE} --ex-dim 10 --seeds 2 --skip-c4 --max-docs 200"
    )
    return json.loads(path.read_text())


def test_model_metadata(smoke_results):
    assert smoke_results["model"] == "openai-community/gpt2"
    assert smoke_results["n_layers"] == 12
    assert smoke_results["hidden_dim"] == 768


def test_partial_corr_schema(smoke_results):
    pc = smoke_results["partial_corr"]
    assert "mean" in pc
    assert "per_seed" in pc
    assert len(pc["per_seed"]) == pc["n_seeds"]
    assert all(isinstance(v, float) for v in pc["per_seed"])


def test_partial_corr_positive(smoke_results):
    assert smoke_results["partial_corr"]["mean"] > 0


def test_test_split_exists(smoke_results):
    tsc = smoke_results["test_split_comparison"]
    assert "mean" in tsc
    assert "per_seed" in tsc


def test_seed_agreement(smoke_results):
    sa = smoke_results["seed_agreement"]
    assert sa["mean"] > 0.5


def test_output_controlled(smoke_results):
    oc = smoke_results["output_controlled"]
    assert "mean" in oc
    assert "per_seed" in oc


def test_baselines(smoke_results):
    bl = smoke_results["baselines"]
    for key in ["ff_goodness", "active_ratio", "act_entropy", "activation_norm", "random_head"]:
        assert key in bl, f"Missing baseline: {key}"


def test_cross_domain(smoke_results):
    cd = smoke_results["cross_domain"]
    assert "wikitext" in cd
    # c4 keys absent when run with --skip-c4
    if "c4" in cd:
        assert "c4_within" in cd


def test_control_sensitivity(smoke_results):
    cs = smoke_results["control_sensitivity"]
    for key in ["none", "softmax_only", "standard", "plus_entropy", "nonlinear"]:
        assert key in cs, f"Missing control: {key}"
    assert cs["none"] > cs["standard"]


def test_flagging(smoke_results):
    fl = smoke_results["flagging_6a"]
    assert "n_tokens" in fl
    assert "summary" in fl
    assert "0.1" in fl["summary"]


def test_layer_profile(smoke_results):
    lp = smoke_results["layer_profile"]
    assert len(lp) == 12
    assert all(isinstance(v, float) for v in lp.values())


# Numerical fingerprint captured from the H100-anchored fixture regen.
# Canonical environment: NVIDIA H100 80GB HBM3, CUDA 12.8, torch
# 2.8.0+cu128, transformers >=4.45, bfloat16. CUDA bf16 matmul has
# run-to-run jitter near 1e-3, so this block reflects the values in the
# committed fixture, not a distribution. Update on intentional regen;
# the test enforces fixture and expected values are committed together.
# On non-canonical hardware (different GPU class, CUDA, or torch
# version), regenerate the fixture and EXPECTED_FINGERPRINT together
# rather than rerunning the existing test against new outputs; the
# 1e-6 tolerance is for fixture-edit detection, not cross-hardware
# numerical agreement.
EXPECTED_FINGERPRINT = {
    "model_revision": "607a30d783dfa663caf39e06633721c8d4cfcd7e",
    "device": "cuda",
    "script": "scripts/run_model.py",
    "value_source": "post_hoc_deterministic",
    "timestamp": "2026-04-14T03:55:02+00:00",
    "peak_layer_final": 6,
    "n_seeds": 2,
    "partial_corr_mean": 0.24683777922796332,
    "partial_corr_per_seed": [0.2383140596045677, 0.25536149885135895],
}
FINGERPRINT_TOL = 1e-6


def test_fixture_fingerprint(smoke_results):
    """Tripwire: fixture file must match the committed fingerprint.

    Catches three failure modes: (1) accidental edit of the fixture JSON,
    (2) regeneration without updating EXPECTED_FINGERPRINT, (3) silent
    drift in producer math that survives schema checks. Tolerance is
    bit-exact for normal floats round-tripping through json.dumps/loads.

    All five canonical provenance fields are asserted so the smoke fixture
    cannot drift independently of the canonical-validator's enforcement.
    """
    prov = smoke_results["provenance"]
    assert prov["model_revision"] == EXPECTED_FINGERPRINT["model_revision"]
    assert prov["device"] == EXPECTED_FINGERPRINT["device"]
    assert prov["script"] == EXPECTED_FINGERPRINT["script"]
    assert prov["value_source"] == EXPECTED_FINGERPRINT["value_source"]
    assert prov["timestamp"] == EXPECTED_FINGERPRINT["timestamp"]
    assert smoke_results["peak_layer_final"] == EXPECTED_FINGERPRINT["peak_layer_final"]
    pc = smoke_results["partial_corr"]
    assert pc["n_seeds"] == EXPECTED_FINGERPRINT["n_seeds"]
    assert abs(pc["mean"] - EXPECTED_FINGERPRINT["partial_corr_mean"]) < FINGERPRINT_TOL
    for actual, expected in zip(pc["per_seed"], EXPECTED_FINGERPRINT["partial_corr_per_seed"]):
        assert abs(actual - expected) < FINGERPRINT_TOL
